server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /gateway-service-api
server.error.whitelabel.enabled: false

logging:
  path: logs
  level: INFO
  level.com.voteva: DEBUG

spring:
  application:
    name: gateway-service-api
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    mode: HTML

gateway:
  grpc.client:
    QuizServiceV1Grpc:
      host: localhost
      port: 6567
    TestsServiceV1Grpc:
      host: localhost
      port: 6566
    UsersServiceV1Grpc:
      host: localhost
      port: 6565
