grpc:
  port: 6566

logging:
  path: logs
  level: INFO
  level.org.hibernate: INFO
  level.com.voteva: DEBUG

spring:
  application:
    name: tests-api
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: tests_db

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

