grpc:
  port: 6567

logging:
  path: logs
  level: INFO
  level.org.hibernate: INFO
  level.com.voteva: DEBUG

spring:
  application:
    name: quiz-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/quiz"
    username: srv_quiz
    password: "0000"

spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
